# 1. Create a null vector of size 10 but the fifth value which is 1.

In [85]:
import numpy as np
x=np.zeros(10)
x[4]=1
print(x)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


# 2. Create a vector with values ranging from 10 to 49.

In [92]:
sa=np.arange(10,49)
print(sa)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48]


# 3.Create a 3x3 matrix with values ranging from 0 to 8

In [87]:
val=np.arange(0,9).reshape(3,3)
val

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

# 4. Find indices of non-zero elements from [1,2,0,0,4,0]

In [89]:
n_array = np.array([1,2,0,0,4,0])
print('original_array',n_array)

res=np.nonzero(n_array)
print(res)


original_array [1 2 0 0 4 0]
(array([0, 1, 4], dtype=int64),)


# Create a 10x10 array with random values and find the minimum and maximum values.

In [90]:
x = np.random.random((10,10))
print("Original Array:")
print(x) 
xmin, xmax = x.min(), x.max()
print("Minimum and Maximum Values:")
print(xmin, xmax)

Original Array:
[[0.35435918 0.25083634 0.21142214 0.39426167 0.26854429 0.74537742
  0.32753682 0.56180479 0.35538424 0.37193128]
 [0.7569312  0.96257976 0.22583336 0.29055805 0.32026801 0.67994955
  0.83051919 0.64861174 0.51195172 0.05599336]
 [0.94284522 0.42516461 0.16960589 0.73198354 0.02219938 0.66447615
  0.64535254 0.09306413 0.37914937 0.78287248]
 [0.09387879 0.25001378 0.21381224 0.70752714 0.99562203 0.9749597
  0.90448354 0.98997922 0.90909085 0.39727252]
 [0.07338792 0.67510621 0.57291306 0.90640708 0.17437235 0.11045405
  0.9022813  0.35626176 0.90898254 0.72855068]
 [0.77101038 0.19225413 0.15798165 0.26997755 0.76884116 0.71213329
  0.87709007 0.16890442 0.480054   0.63057878]
 [0.71176473 0.62897496 0.82676134 0.60261282 0.68658167 0.33576333
  0.54888386 0.46087525 0.66614834 0.08052619]
 [0.96547454 0.85208477 0.98443553 0.10356154 0.77494218 0.96300637
  0.82428714 0.17786639 0.61073925 0.02298685]
 [0.45973612 0.46383552 0.36972354 0.73925832 0.60033321 0.451654

# 6. Create a random vector of size 30 and find the mean value.

In [91]:
a=np.random.random(30)
print(a)

print("The Mean Value is: ")
a.mean()

[0.7154758  0.51901476 0.29055818 0.23307859 0.03833084 0.78509951
 0.99396895 0.7003535  0.94700148 0.97327897 0.70294381 0.05263548
 0.0343059  0.83950131 0.06698861 0.10865661 0.59299792 0.97484359
 0.92619889 0.76008759 0.85021781 0.57053698 0.91491439 0.21628924
 0.19889667 0.09610979 0.27066655 0.58373586 0.52788516 0.85237362]
The Mean Value is: 


0.5445648784544183